//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECXSecurityAccess
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CApplication", Namespace="http://tempuri.org/")]
    public partial class CApplication : object
    {
        
        private int IdField;
        
        private string UniqueIdentifierField;
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UniqueIdentifier
        {
            get
            {
                return this.UniqueIdentifierField;
            }
            set
            {
                this.UniqueIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfFloat", Namespace="http://tempuri.org/", ItemName="float")]
    public class ArrayOfFloat : System.Collections.Generic.List<float>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://tempuri.org/", ItemName="boolean")]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAuditTrial", Namespace="http://tempuri.org/")]
    public partial class CAuditTrial : object
    {
        
        private string ModuleCodeField;
        
        private string UserGuidField;
        
        private string OldValueField;
        
        private string NewValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ModuleCode
        {
            get
            {
                return this.ModuleCodeField;
            }
            set
            {
                this.ModuleCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OldValue
        {
            get
            {
                return this.OldValueField;
            }
            set
            {
                this.OldValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NewValue
        {
            get
            {
                return this.NewValueField;
            }
            set
            {
                this.NewValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationStatus", Namespace="http://tempuri.org/")]
    public enum AuthenticationStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessGranted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoApplicationAccess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUserOrPassword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OUser", Namespace="http://tempuri.org/")]
    public partial class OUser : object
    {
        
        private string UserGuidField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ECXSecurityAccess.ECXSecurityAccessSoap")]
    public interface ECXSecurityAccessSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActiveApplications", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.GetActiveApplicationsResponse> GetActiveApplicationsAsync(ECXSecurityAccess.GetActiveApplicationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasRight", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.HasRightResponse> HasRightAsync(ECXSecurityAccess.HasRightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasRights", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.HasRightsResponse> HasRightsAsync(ECXSecurityAccess.HasRightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserHasApplicationAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.UserHasApplicationAccessResponse> UserHasApplicationAccessAsync(ECXSecurityAccess.UserHasApplicationAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserHasApplicationsAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.UserHasApplicationsAccessResponse> UserHasApplicationsAccessAsync(ECXSecurityAccess.UserHasApplicationsAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAuditTrail", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.AddAuditTrailResponse> AddAuditTrailAsync(ECXSecurityAccess.AddAuditTrailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAuditTrails", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.AddAuditTrailsResponse> AddAuditTrailsAsync(ECXSecurityAccess.AddAuditTrailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuditTrailCommit", ReplyAction="*")]
        System.Threading.Tasks.Task AuditTrailCommitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuditTrailRollback", ReplyAction="*")]
        System.Threading.Tasks.Task AuditTrailRollbackAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAuthenticated", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.IsAuthenticatedResponse> IsAuthenticatedAsync(ECXSecurityAccess.IsAuthenticatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserHasLocationAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.UserHasLocationAccessResponse> UserHasLocationAccessAsync(ECXSecurityAccess.UserHasLocationAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsersWithRight", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.UsersWithRightResponse> UsersWithRightAsync(ECXSecurityAccess.UsersWithRightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<ECXSecurityAccess.GetUserNameResponse> GetUserNameAsync(ECXSecurityAccess.GetUserNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveApplicationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveApplications", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.GetActiveApplicationsRequestBody Body;
        
        public GetActiveApplicationsRequest()
        {
        }
        
        public GetActiveApplicationsRequest(ECXSecurityAccess.GetActiveApplicationsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetActiveApplicationsRequestBody
    {
        
        public GetActiveApplicationsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveApplicationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveApplicationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.GetActiveApplicationsResponseBody Body;
        
        public GetActiveApplicationsResponse()
        {
        }
        
        public GetActiveApplicationsResponse(ECXSecurityAccess.GetActiveApplicationsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActiveApplicationsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECXSecurityAccess.CApplication[] GetActiveApplicationsResult;
        
        public GetActiveApplicationsResponseBody()
        {
        }
        
        public GetActiveApplicationsResponseBody(ECXSecurityAccess.CApplication[] GetActiveApplicationsResult)
        {
            this.GetActiveApplicationsResult = GetActiveApplicationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRight", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.HasRightRequestBody Body;
        
        public HasRightRequest()
        {
        }
        
        public HasRightRequest(ECXSecurityAccess.HasRightRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LocationCode;
        
        public HasRightRequestBody()
        {
        }
        
        public HasRightRequestBody(string UserGuid, string Code, string LocationCode)
        {
            this.UserGuid = UserGuid;
            this.Code = Code;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.HasRightResponseBody Body;
        
        public HasRightResponse()
        {
        }
        
        public HasRightResponse(ECXSecurityAccess.HasRightResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float HasRightResult;
        
        public HasRightResponseBody()
        {
        }
        
        public HasRightResponseBody(float HasRightResult)
        {
            this.HasRightResult = HasRightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRights", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.HasRightsRequestBody Body;
        
        public HasRightsRequest()
        {
        }
        
        public HasRightsRequest(ECXSecurityAccess.HasRightsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ECXSecurityAccess.ArrayOfString Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LocationCode;
        
        public HasRightsRequestBody()
        {
        }
        
        public HasRightsRequestBody(string UserGuid, ECXSecurityAccess.ArrayOfString Code, string LocationCode)
        {
            this.UserGuid = UserGuid;
            this.Code = Code;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRightsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.HasRightsResponseBody Body;
        
        public HasRightsResponse()
        {
        }
        
        public HasRightsResponse(ECXSecurityAccess.HasRightsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECXSecurityAccess.ArrayOfFloat HasRightsResult;
        
        public HasRightsResponseBody()
        {
        }
        
        public HasRightsResponseBody(ECXSecurityAccess.ArrayOfFloat HasRightsResult)
        {
            this.HasRightsResult = HasRightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationAccessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationAccess", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UserHasApplicationAccessRequestBody Body;
        
        public UserHasApplicationAccessRequest()
        {
        }
        
        public UserHasApplicationAccessRequest(ECXSecurityAccess.UserHasApplicationAccessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationAccessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApplicationCode;
        
        public UserHasApplicationAccessRequestBody()
        {
        }
        
        public UserHasApplicationAccessRequestBody(string UserGuid, string ApplicationCode)
        {
            this.UserGuid = UserGuid;
            this.ApplicationCode = ApplicationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationAccessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationAccessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UserHasApplicationAccessResponseBody Body;
        
        public UserHasApplicationAccessResponse()
        {
        }
        
        public UserHasApplicationAccessResponse(ECXSecurityAccess.UserHasApplicationAccessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationAccessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserHasApplicationAccessResult;
        
        public UserHasApplicationAccessResponseBody()
        {
        }
        
        public UserHasApplicationAccessResponseBody(bool UserHasApplicationAccessResult)
        {
            this.UserHasApplicationAccessResult = UserHasApplicationAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationsAccessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationsAccess", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UserHasApplicationsAccessRequestBody Body;
        
        public UserHasApplicationsAccessRequest()
        {
        }
        
        public UserHasApplicationsAccessRequest(ECXSecurityAccess.UserHasApplicationsAccessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationsAccessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ECXSecurityAccess.ArrayOfString ApplicationCode;
        
        public UserHasApplicationsAccessRequestBody()
        {
        }
        
        public UserHasApplicationsAccessRequestBody(string UserGuid, ECXSecurityAccess.ArrayOfString ApplicationCode)
        {
            this.UserGuid = UserGuid;
            this.ApplicationCode = ApplicationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationsAccessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationsAccessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UserHasApplicationsAccessResponseBody Body;
        
        public UserHasApplicationsAccessResponse()
        {
        }
        
        public UserHasApplicationsAccessResponse(ECXSecurityAccess.UserHasApplicationsAccessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationsAccessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECXSecurityAccess.ArrayOfBoolean UserHasApplicationsAccessResult;
        
        public UserHasApplicationsAccessResponseBody()
        {
        }
        
        public UserHasApplicationsAccessResponseBody(ECXSecurityAccess.ArrayOfBoolean UserHasApplicationsAccessResult)
        {
            this.UserHasApplicationsAccessResult = UserHasApplicationsAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrail", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.AddAuditTrailRequestBody Body;
        
        public AddAuditTrailRequest()
        {
        }
        
        public AddAuditTrailRequest(ECXSecurityAccess.AddAuditTrailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModuleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OldValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NewValue;
        
        public AddAuditTrailRequestBody()
        {
        }
        
        public AddAuditTrailRequestBody(string ModuleCode, string UserGuid, string OldValue, string NewValue)
        {
            this.ModuleCode = ModuleCode;
            this.UserGuid = UserGuid;
            this.OldValue = OldValue;
            this.NewValue = NewValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.AddAuditTrailResponseBody Body;
        
        public AddAuditTrailResponse()
        {
        }
        
        public AddAuditTrailResponse(ECXSecurityAccess.AddAuditTrailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddAuditTrailResult;
        
        public AddAuditTrailResponseBody()
        {
        }
        
        public AddAuditTrailResponseBody(bool AddAuditTrailResult)
        {
            this.AddAuditTrailResult = AddAuditTrailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrails", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.AddAuditTrailsRequestBody Body;
        
        public AddAuditTrailsRequest()
        {
        }
        
        public AddAuditTrailsRequest(ECXSecurityAccess.AddAuditTrailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECXSecurityAccess.CAuditTrial[] AuditTrialList;
        
        public AddAuditTrailsRequestBody()
        {
        }
        
        public AddAuditTrailsRequestBody(ECXSecurityAccess.CAuditTrial[] AuditTrialList)
        {
            this.AuditTrialList = AuditTrialList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.AddAuditTrailsResponseBody Body;
        
        public AddAuditTrailsResponse()
        {
        }
        
        public AddAuditTrailsResponse(ECXSecurityAccess.AddAuditTrailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddAuditTrailsResult;
        
        public AddAuditTrailsResponseBody()
        {
        }
        
        public AddAuditTrailsResponseBody(bool AddAuditTrailsResult)
        {
            this.AddAuditTrailsResult = AddAuditTrailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticated", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.IsAuthenticatedRequestBody Body;
        
        public IsAuthenticatedRequest()
        {
        }
        
        public IsAuthenticatedRequest(ECXSecurityAccess.IsAuthenticatedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApplicationCode;
        
        public IsAuthenticatedRequestBody()
        {
        }
        
        public IsAuthenticatedRequestBody(string username, string Password, string ApplicationCode)
        {
            this.username = username;
            this.Password = Password;
            this.ApplicationCode = ApplicationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticatedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.IsAuthenticatedResponseBody Body;
        
        public IsAuthenticatedResponse()
        {
        }
        
        public IsAuthenticatedResponse(ECXSecurityAccess.IsAuthenticatedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ECXSecurityAccess.AuthenticationStatus IsAuthenticatedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserGuid;
        
        public IsAuthenticatedResponseBody()
        {
        }
        
        public IsAuthenticatedResponseBody(ECXSecurityAccess.AuthenticationStatus IsAuthenticatedResult, string UserGuid)
        {
            this.IsAuthenticatedResult = IsAuthenticatedResult;
            this.UserGuid = UserGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasLocationAccessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasLocationAccess", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UserHasLocationAccessRequestBody Body;
        
        public UserHasLocationAccessRequest()
        {
        }
        
        public UserHasLocationAccessRequest(ECXSecurityAccess.UserHasLocationAccessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasLocationAccessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LocationCode;
        
        public UserHasLocationAccessRequestBody()
        {
        }
        
        public UserHasLocationAccessRequestBody(string UserGuid, string LocationCode)
        {
            this.UserGuid = UserGuid;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasLocationAccessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasLocationAccessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UserHasLocationAccessResponseBody Body;
        
        public UserHasLocationAccessResponse()
        {
        }
        
        public UserHasLocationAccessResponse(ECXSecurityAccess.UserHasLocationAccessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasLocationAccessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserHasLocationAccessResult;
        
        public UserHasLocationAccessResponseBody()
        {
        }
        
        public UserHasLocationAccessResponseBody(bool UserHasLocationAccessResult)
        {
            this.UserHasLocationAccessResult = UserHasLocationAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersWithRightRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersWithRight", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UsersWithRightRequestBody Body;
        
        public UsersWithRightRequest()
        {
        }
        
        public UsersWithRightRequest(ECXSecurityAccess.UsersWithRightRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsersWithRightRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LocationCode;
        
        public UsersWithRightRequestBody()
        {
        }
        
        public UsersWithRightRequestBody(string Code, string LocationCode)
        {
            this.Code = Code;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersWithRightResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersWithRightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.UsersWithRightResponseBody Body;
        
        public UsersWithRightResponse()
        {
        }
        
        public UsersWithRightResponse(ECXSecurityAccess.UsersWithRightResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsersWithRightResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECXSecurityAccess.OUser[] UsersWithRightResult;
        
        public UsersWithRightResponseBody()
        {
        }
        
        public UsersWithRightResponseBody(ECXSecurityAccess.OUser[] UsersWithRightResult)
        {
            this.UsersWithRightResult = UsersWithRightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserName", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.GetUserNameRequestBody Body;
        
        public GetUserNameRequest()
        {
        }
        
        public GetUserNameRequest(ECXSecurityAccess.GetUserNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        public GetUserNameRequestBody()
        {
        }
        
        public GetUserNameRequestBody(string Id)
        {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECXSecurityAccess.GetUserNameResponseBody Body;
        
        public GetUserNameResponse()
        {
        }
        
        public GetUserNameResponse(ECXSecurityAccess.GetUserNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserNameResult;
        
        public GetUserNameResponseBody()
        {
        }
        
        public GetUserNameResponseBody(string GetUserNameResult)
        {
            this.GetUserNameResult = GetUserNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ECXSecurityAccessSoapChannel : ECXSecurityAccess.ECXSecurityAccessSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ECXSecurityAccessSoapClient : System.ServiceModel.ClientBase<ECXSecurityAccess.ECXSecurityAccessSoap>, ECXSecurityAccess.ECXSecurityAccessSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ECXSecurityAccessSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ECXSecurityAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), ECXSecurityAccessSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ECXSecurityAccessSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ECXSecurityAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ECXSecurityAccessSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ECXSecurityAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ECXSecurityAccessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.GetActiveApplicationsResponse> ECXSecurityAccess.ECXSecurityAccessSoap.GetActiveApplicationsAsync(ECXSecurityAccess.GetActiveApplicationsRequest request)
        {
            return base.Channel.GetActiveApplicationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.GetActiveApplicationsResponse> GetActiveApplicationsAsync()
        {
            ECXSecurityAccess.GetActiveApplicationsRequest inValue = new ECXSecurityAccess.GetActiveApplicationsRequest();
            inValue.Body = new ECXSecurityAccess.GetActiveApplicationsRequestBody();
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).GetActiveApplicationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.HasRightResponse> ECXSecurityAccess.ECXSecurityAccessSoap.HasRightAsync(ECXSecurityAccess.HasRightRequest request)
        {
            return base.Channel.HasRightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.HasRightResponse> HasRightAsync(string UserGuid, string Code, string LocationCode)
        {
            ECXSecurityAccess.HasRightRequest inValue = new ECXSecurityAccess.HasRightRequest();
            inValue.Body = new ECXSecurityAccess.HasRightRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.Code = Code;
            inValue.Body.LocationCode = LocationCode;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).HasRightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.HasRightsResponse> ECXSecurityAccess.ECXSecurityAccessSoap.HasRightsAsync(ECXSecurityAccess.HasRightsRequest request)
        {
            return base.Channel.HasRightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.HasRightsResponse> HasRightsAsync(string UserGuid, ECXSecurityAccess.ArrayOfString Code, string LocationCode)
        {
            ECXSecurityAccess.HasRightsRequest inValue = new ECXSecurityAccess.HasRightsRequest();
            inValue.Body = new ECXSecurityAccess.HasRightsRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.Code = Code;
            inValue.Body.LocationCode = LocationCode;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).HasRightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.UserHasApplicationAccessResponse> ECXSecurityAccess.ECXSecurityAccessSoap.UserHasApplicationAccessAsync(ECXSecurityAccess.UserHasApplicationAccessRequest request)
        {
            return base.Channel.UserHasApplicationAccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.UserHasApplicationAccessResponse> UserHasApplicationAccessAsync(string UserGuid, string ApplicationCode)
        {
            ECXSecurityAccess.UserHasApplicationAccessRequest inValue = new ECXSecurityAccess.UserHasApplicationAccessRequest();
            inValue.Body = new ECXSecurityAccess.UserHasApplicationAccessRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.ApplicationCode = ApplicationCode;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).UserHasApplicationAccessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.UserHasApplicationsAccessResponse> ECXSecurityAccess.ECXSecurityAccessSoap.UserHasApplicationsAccessAsync(ECXSecurityAccess.UserHasApplicationsAccessRequest request)
        {
            return base.Channel.UserHasApplicationsAccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.UserHasApplicationsAccessResponse> UserHasApplicationsAccessAsync(string UserGuid, ECXSecurityAccess.ArrayOfString ApplicationCode)
        {
            ECXSecurityAccess.UserHasApplicationsAccessRequest inValue = new ECXSecurityAccess.UserHasApplicationsAccessRequest();
            inValue.Body = new ECXSecurityAccess.UserHasApplicationsAccessRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.ApplicationCode = ApplicationCode;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).UserHasApplicationsAccessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.AddAuditTrailResponse> ECXSecurityAccess.ECXSecurityAccessSoap.AddAuditTrailAsync(ECXSecurityAccess.AddAuditTrailRequest request)
        {
            return base.Channel.AddAuditTrailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.AddAuditTrailResponse> AddAuditTrailAsync(string ModuleCode, string UserGuid, string OldValue, string NewValue)
        {
            ECXSecurityAccess.AddAuditTrailRequest inValue = new ECXSecurityAccess.AddAuditTrailRequest();
            inValue.Body = new ECXSecurityAccess.AddAuditTrailRequestBody();
            inValue.Body.ModuleCode = ModuleCode;
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.OldValue = OldValue;
            inValue.Body.NewValue = NewValue;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).AddAuditTrailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.AddAuditTrailsResponse> ECXSecurityAccess.ECXSecurityAccessSoap.AddAuditTrailsAsync(ECXSecurityAccess.AddAuditTrailsRequest request)
        {
            return base.Channel.AddAuditTrailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.AddAuditTrailsResponse> AddAuditTrailsAsync(ECXSecurityAccess.CAuditTrial[] AuditTrialList)
        {
            ECXSecurityAccess.AddAuditTrailsRequest inValue = new ECXSecurityAccess.AddAuditTrailsRequest();
            inValue.Body = new ECXSecurityAccess.AddAuditTrailsRequestBody();
            inValue.Body.AuditTrialList = AuditTrialList;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).AddAuditTrailsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task AuditTrailCommitAsync()
        {
            return base.Channel.AuditTrailCommitAsync();
        }
        
        public System.Threading.Tasks.Task AuditTrailRollbackAsync()
        {
            return base.Channel.AuditTrailRollbackAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.IsAuthenticatedResponse> ECXSecurityAccess.ECXSecurityAccessSoap.IsAuthenticatedAsync(ECXSecurityAccess.IsAuthenticatedRequest request)
        {
            return base.Channel.IsAuthenticatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.IsAuthenticatedResponse> IsAuthenticatedAsync(string username, string Password, string ApplicationCode)
        {
            ECXSecurityAccess.IsAuthenticatedRequest inValue = new ECXSecurityAccess.IsAuthenticatedRequest();
            inValue.Body = new ECXSecurityAccess.IsAuthenticatedRequestBody();
            inValue.Body.username = username;
            inValue.Body.Password = Password;
            inValue.Body.ApplicationCode = ApplicationCode;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).IsAuthenticatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.UserHasLocationAccessResponse> ECXSecurityAccess.ECXSecurityAccessSoap.UserHasLocationAccessAsync(ECXSecurityAccess.UserHasLocationAccessRequest request)
        {
            return base.Channel.UserHasLocationAccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.UserHasLocationAccessResponse> UserHasLocationAccessAsync(string UserGuid, string LocationCode)
        {
            ECXSecurityAccess.UserHasLocationAccessRequest inValue = new ECXSecurityAccess.UserHasLocationAccessRequest();
            inValue.Body = new ECXSecurityAccess.UserHasLocationAccessRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.LocationCode = LocationCode;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).UserHasLocationAccessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.UsersWithRightResponse> ECXSecurityAccess.ECXSecurityAccessSoap.UsersWithRightAsync(ECXSecurityAccess.UsersWithRightRequest request)
        {
            return base.Channel.UsersWithRightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.UsersWithRightResponse> UsersWithRightAsync(string Code, string LocationCode)
        {
            ECXSecurityAccess.UsersWithRightRequest inValue = new ECXSecurityAccess.UsersWithRightRequest();
            inValue.Body = new ECXSecurityAccess.UsersWithRightRequestBody();
            inValue.Body.Code = Code;
            inValue.Body.LocationCode = LocationCode;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).UsersWithRightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECXSecurityAccess.GetUserNameResponse> ECXSecurityAccess.ECXSecurityAccessSoap.GetUserNameAsync(ECXSecurityAccess.GetUserNameRequest request)
        {
            return base.Channel.GetUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECXSecurityAccess.GetUserNameResponse> GetUserNameAsync(string Id)
        {
            ECXSecurityAccess.GetUserNameRequest inValue = new ECXSecurityAccess.GetUserNameRequest();
            inValue.Body = new ECXSecurityAccess.GetUserNameRequestBody();
            inValue.Body.Id = Id;
            return ((ECXSecurityAccess.ECXSecurityAccessSoap)(this)).GetUserNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.5.20:5000/ECXSecurity/ECXSecurityAccess.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.5.20:5000/ECXSecurity/ECXSecurityAccess.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ECXSecurityAccessSoap,
            
            ECXSecurityAccessSoap12,
        }
    }
}
